import os
import shutil
import re

log_lines = """
 rename {public/portfolio_data/images => unused-assests}/001_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/002_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/004_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/005_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/006_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/007_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/008_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/009_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/010_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/011_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/017_.jpg (100%)
 rename {public/portfolio_data/images => unused-assests}/021_.jpg (100%)
 rename {public/Images-works => unused-assests}/14%20pro-01%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/255A1123 (1).jpg (100%)
 rename {public => unused-assests}/28390e68-2146-4732-826b-f44d09598f2a.jpeg (100%)
 rename {public => unused-assests}/ChatGPT Image May 7, 2026, 11_43_55 AM.png (100%)
 rename {public => unused-assests}/ChatGPT Image May 7, 2026, 11_53_00 AM AND.png (100%)
 rename {public => unused-assests}/ChatGPT Image May 7, 2026, 11_53_00 AM.png (100%)
 rename {public/LOGOS => unused-assests}/El logo.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_5wdc7d5wdc7d5wdc.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_6vq106vq106vq106 (1).png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_7lli67lli67lli67.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_9rrwc79rrwc79rrw.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_kkd9wtkkd9wtkkd9.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_m665tsm665tsm665.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_nvors3nvors3nvor-Photoroom.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_tu344tu344tu344t-Photoroom.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_uatnsjuatnsjuatn-Photoroom.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_uk34esuk34esuk34.png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_vfxcssvfxcssvfxc (1).png (100%)
 rename {public => unused-assests}/Gemini_Generated_Image_wxxhc2wxxhc2wxxh-Photoroom.png (100%)
 rename {public/Images-works => unused-assests}/HER%20STORY%20PSD%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/JNE_W_B_V_VTSGTS_B_G_videomp_.mp4 (100%)
 rename {public => unused-assests}/PHOTO-2026-05-07-11-20-50.jpg (100%)
 rename {public => unused-assests}/PHOTO-2026-05-07-12-51-11.jpg (100%)
 rename {public => unused-assests}/PHOTO-2026-05-07-13-53-20-Photoroom.png (100%)
 rename {public/LOGOS => unused-assests}/PHOTO-2026-05-07-13-53-20.jpg (100%)
 rename {public => unused-assests}/PHOTO-2026-05-07-14-28-31.jpg (100%)
 rename {public/Images-works => unused-assests}/SNOW%20WORLD%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/Sunflower_Logo_Animation_with_Butterfly.mp4 (100%)
 rename {public => unused-assests}/about us 1.png (100%)
 rename {public => unused-assests}/about us 2.png (100%)
 rename {public/Images-works => unused-assests}/bmw%20SMP%20copy.jpg.jpeg (100%)
 rename {public/Images-works => unused-assests}/bottle%20logo%20mockup%20copy.jpg.jpeg (100%)
 rename {public/Images-works => unused-assests}/cafe%20logo%20copy.jpg.jpeg (100%)
 rename {public/Images-works => unused-assests}/cup%20mockup%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/cursor-sunflower.png (100%)
 rename {public => unused-assests}/f_e_e_d_d_a_f_b_mp_.mp4 (100%)
 rename {public => unused-assests}/image-Photoroom (1).png (100%)
 rename {public => unused-assests}/image-Photoroom (2).png (100%)
 rename {public => unused-assests}/image-Photoroom (3).png (100%)
 rename {public => unused-assests}/image-Photoroom (5).png (100%)
 rename {public => unused-assests}/image-Photoroom (6).png (100%)
 rename {public => unused-assests}/image-PhotoroomLOGO(2).png (100%)
 rename {public/Images-works => unused-assests}/jbl%20socialmedia%20mockup%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/marketing_strategy_1777907706366.png (100%)
 rename {public => unused-assests}/paid_ads_1777907727018.png (100%)
 rename {public => unused-assests}/photo_video_1777907763009.png (100%)
 rename {public/LOGOS => unused-assests}/sakarya.png (100%)
 rename {public => unused-assests}/sam shoting in sunflower garden.png (100%)
 rename {public => unused-assests}/service_prop_sunflower_butterfly_1777907794965.png (100%)
 rename {public/Images-works => unused-assests}/shopping%20offer.jpg.jpeg (100%)
 rename {public/Images-works => unused-assests}/showflick%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/social_media_mgmt_1777907673000.png (100%)
 rename {public => unused-assests}/web_design_1777907780054.png (100%)
 rename {public/Images-works => unused-assests}/wedding%20magazine%20%20copy.jpg.jpeg (100%)
 rename {public => unused-assests}/wedding_content_1777907743808.png (100%)
 rename {public/portfolio_data/images => unused-assests}/work_furn_main.png (100%)
 rename {public/portfolio_data/images => unused-assests}/work_furn_sec.png (100%)
 rename {public/portfolio_data/images => unused-assests}/work_rest_main.png (100%)
 rename {public/portfolio_data/images => unused-assests}/work_rest_sec.png (100%)
"""

def main():
    root_dir = os.getcwd()
    unused_dir = os.path.join(root_dir, 'unused-assests')
    
    for line in log_lines.strip().split('\n'):
        # Parse lines like: rename {public/portfolio_data/images => unused-assests}/001_.jpg (100%)
        # or rename {public => unused-assests}/PHOTO-2026.jpg
        match = re.search(r'rename \{(.+?) => unused-assests\}/(.+) \(\d+%\)', line)
        if match:
            original_dir = match.group(1)
            filename = match.group(2)
            
            # Reconstruct paths
            current_path = os.path.join(unused_dir, filename)
            original_path = os.path.join(root_dir, original_dir, filename)
            
            if os.path.exists(current_path):
                print(f"Restoring {filename} to {original_dir}")
                os.makedirs(os.path.dirname(original_path), exist_ok=True)
                shutil.move(current_path, original_path)

if __name__ == '__main__':
    main()
